from pathlib import Path
from cryptography.fernet import Fernet
import pyautogui
import subprocess
import time
import os

""" 
Path to the key and encrypted password files
These files should be generated by keys.py script.
"""

s_key_file = "secret.key"
s_enc_file = "encrypted_password.bin"

"""
Check if the key and encrypted password files exist, if not, run keys.py to generate them 

This is a one-time setup step. unless the key or password changes or removed in error, you do not need to run this again.

"""

if not Path(s_key_file).is_file() or not Path(s_enc_file).is_file():
    print("Key or encrypted password file not found. Generating them...")
    subprocess.run(["python", "keys.py"])
else:
    print("Key and encrypted password file found. Proceeding to decrypt the password.")

""" 
Load key and encrypted password 
This assumes that the key and encrypted password files are in the same directory as this script.
If they are in a different directory, adjust the paths accordingly.
"""

with open("secret.key", "rb") as key_file:

    key = key_file.read()

f = Fernet(key)

with open("encrypted_password.bin", "rb") as enc_file:

    encrypted = enc_file.read()

password = f.decrypt(encrypted).decode()

"""
Launch the DSN software application
This assumes that the DSN software executable is located at the specified path.
Adjust the path if necessary.
"""

subprocess.Popen(r"C:\DSN Software Inc\DSNSoftware\DSN.Exec.WPF.exe")

time.sleep(10)

# Send credentials

# Send credentials

pyautogui.write('dsnadmin')

pyautogui.press('tab')

pyautogui.write(password)

pyautogui.press('enter')
pyautogui.press('enter')